[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gplibrary"
version = "0.1.0"
description = "Python package for probabilistic GP-based surrogate models"
authors = [
    { name = "Alberto Perlini", email = "alberto.perlini@polimi.it" }
]

# Optional: project dependencies (same as pip install)
dependencies = [ 
    "numpy", 
    "scipy",
    "scikit-learn",
]

[tool.setuptools.packages.find]
where = ["src"]
