[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "uqlib"
version = "0.1.0"
description = "Python package for probabilistic surrogate models and uncertainty quantification"
authors = [
    { name = "Alberto Perlini", email = "alberto.perlini@polimi.it" }
]

# Optional: project dependencies (same as pip install)
dependencies = [ 
    "numpy", 
    "scipy",
    "scikit-learn",
]

